### ISSUE TITLE
New API fields

### ISSUE THREAD

**Issue by LukaszRados** [ericromanenghi/kaorimua#1]
Hi Eric,

there are some fields I would love to see in API responses. Are you able to provide them?

1. Currently each photo has an `id`, `filename` and `gallery_id`. Could they please have `width` and `height` as well? I need it to make galleries nice and fast. I need it in following endpoint: `/gallery/{gallery_id}`. 
2. Just as a nice touch: could you please generate `slug` for each gallery and return this? We could have nice urls like `kaorimua.nl/work/karolijn` instead of `kaorimua.nl/work/1`. I need it in following endpoint: `/gallery/all`.
3. For the gallery: I was thinking about adding more data than just name. Like photographer name and model name, what do you think? 

Thank you in advance.

**Comment by ericromanenghi** [comment]
Thanks for feedback! I'll work on it over the weekend!

**Comment by ericromanenghi** [comment]
I just added width and height in the commit https://github.com/ericromanenghi/kaorimua/commit/5cfa000822b03ee5aa36189d89e4f0682311ee58, please let me know if it's working as you expected.

Please note that you will need to remove the file backend/db/app-dev.db because I change the db structure in order to store this values (they will be calculated and stored during file upload).

The other 2 points are still pendent =)

**Comment by ericromanenghi** [comment]
Added slug to gallery: https://github.com/ericromanenghi/kaorimua/commit/574ea141e516adf74b580750ce41821874fa2424

**Comment by ericromanenghi** [comment]
Added photographer and model to gallery: https://github.com/ericromanenghi/kaorimua/commit/ec734fccfad239d24cab532281cb548237235f99
